class MainLocators:
    FOOTER = "footer"
    FOOTER_INFORMATION = "*//h5[contains(text(), 'Information')]"
    FOOTER_CUSTOMER_SERVICE = "*//h5[contains(text(), 'Customer Service')]"
    FOOTER_EXTRAS = "*//h5[contains(text(), 'Extras')]"
    FOOTER_MY_ACCOUNT = "*//h5[contains(text(), 'My Account')]"
    SEARCH_INPUT = "form-control.input-lg"
    SEARCH_BTN = "btn.btn-default.btn-lg"
    SEARCH_TITLE = "*//h1[contains(text(), 'Search - iphone')]"
    PRODUCT_NAME = "*//a[contains(text(), 'iPhone')]"
    BTNS_ADD_TO_CART = "button-group"
    CARD_TOTAL = 'cart-total'
    NAVBAR = "nav.navbar-nav"
    ALERT_NOT_MATCH_KEYPAIR = "alert.alert-danger.alert-dismissible"
    ALERT_SUCCESS_FORGOTTEN_PASWORD = "alert.alert-success.alert-dismissible"
    FORGOTTEN_PASSWORD = "*//a[contains(text(), 'Forgotten Password')]"
    EMAIL_FIELD = "input-email"
